### ISSUE TITLE
При определённых условиях операции добавления фигур не отменяются через Undo

### ISSUE THREAD

**Issue by alexey-malov** [KonstantinGeist/TestApplication#1]
Видео, воспроизводящее данную проблему
https://youtu.be/94blPNUbsSU

**Comment by KonstantinGeist** [comment]
В Presenter.cpp стоит искусственный лимит на число undo:

https://github.com/KonstantinGeist/TestApplication/blob/47e101354b4567cf6bbbdb0c49a8c72215a79b78/TestApplication/Presenter.cpp#L17

Его следует полностью убрать или поднять до более высокого значения?

**Comment by alexey-malov** [comment]
По возможности сделать глубину history неограниченной (ограничить размерами коллекций, хранящих данные). Ревью архитектуры еще буду проводить более подробно. Пока на работе загружен.

**Comment by KonstantinGeist** [comment]
История сделана неограниченной в коммите 2d59fb6114379c077845813ca3c0805878e5a6f9
