### ISSUE TITLE
Смена выделения фигур не должна записыватся в историю правок в виде самостоятельной команды

### ISSUE THREAD

**Issue by alexey-malov** [KonstantinGeist/TestApplication#2]
Действия, которые не меняют состояние холста или его объектов, не должны записываться в историю команд (например, смена выделения). Однако может оказаться удобным выполнять выделение объекта при отмене или повторе команд.
Например, при отмене команды удаления объекта разумно выделить восстановленный объект. Либо при отмене/повторе команды ресайза/переноса объекта выполнять его выделение.

**Comment by KonstantinGeist** [comment]
Выделение было записано в историю команд, так как я посчитал, что это было бы удобно в перспективе, если добавлена возможность выделять несколько объектов сразу, особенно если объектов много на холсте - при случайной потере выделения пользователю пришлось бы выделять все объекты заново.

В любом случае, выделение больше не добавляется в историю; вместо этого выделяется последний объект undo/redo: 481786296cbeacfb3fc981de8f65d8304a2ffc9d

**Comment by alexey-malov** [comment]
Выделение используется для задания контекста операции редактирования. 
Действительно, в некоторых приложениях (например, в редакторах растровой графики, вроде Photoshop, GIMP, Paint.NET) задание выделения может быть трудоёмким для пользователя и поэтому добавляется в историю команд, во многих других редакторах (обычно это редакторы, где объекты на холсте выделяются по клику по ним, а также текстовые редакторы или 3D редакторы), область выделения в историю команд не записывается.

В случае твоего приложения, близким аналогом является PowerPoint, в котором выделение не кладётся в историю в виде отдельной команды.
