### ISSUE TITLE
Потенциальное неопределённое поведение при удалении полиморфных объектов

### ISSUE THREAD

**Issue by alexey-malov** [KonstantinGeist/TestApplication#3]
[C.35: A base class destructor should be either public and virtual, or protected and nonvirtual](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-dtor-virtual)

Сейчас проблема не возникает только благодаря использованию shared_ptr, который помнит тип того объекта, который надо удалять (при условии, что мы создали объект при помощи make_shared либо передали указатель на реальный тип объекта (а не на базовый) в конструктор shared_ptr). При слегка ином конструировании объекта будут проблемы:
```c++
#include <memory>
#include <iostream>

struct Base
{
	// If you comment base virtual destructor or make it non virtual, 
	// the derived class' destructor won't be called
	virtual ~Base() = default;
};

struct Derived : Base
{
	~Derived()
	{
		std::cout << "destructor called\n";
	}
};

int main()
{
	std::unique_ptr<Base> derived = std::make_unique<Derived>();
	std::shared_ptr<Base> base(std::move(derived));
	return 0;
}
```

**Comment by KonstantinGeist** [comment]
Согласен, упустил момент. В своих проектах пишу под свой старый фреймворк, где все объекты с identity наследуют базовый класс Object, в котором виртуальный деструктор уже определён, поэтому из головы совершенно вылетело, что для новой inheritance chain нужно делать всё по новой. Возьму на заметку.

Надеюсь, это исправлено в 75c3bc45bb60233f99d6cd66e342000e5bfd8486
