### ISSUE TITLE
Замечания по реализации механизма Undo/Redo

### ISSUE THREAD

**Issue by alexey-malov** [KonstantinGeist/TestApplication#4]
В коде были упомянуты 2 возможных подхода к реализации истории:
* Создание snapshot-ов. (кстати, Copy-On-Write может существенно снизить объем потребляемой снапшотами памяти)
* [Паттерн "Команда"](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F))
В программе был использован вариант паттерна "Команда".

Есть идеи, что в нём можно было бы улучшить:

Сейчас методы Do()/Undo()/Redo() класса CAction принимают параметр CUndoContext, через который узнают о "внешнем мире". С этим есть пара моменттов:
* Передача application-specific контекста затрудняет повторное использование класса CAction и списка действий в других приложениях. 
* При росте сложности приложения интерфейс CUndoContext (либо доступные через него объекты) будут слишком сильно разрастаться, чтобы классы конкретных действий могли добраться до нужных им объектов модели

Сделать классы действий независимыми от приложения можно, передавая информацию о контексте выполнения в конструктор класса конкретных действий. В этом случае базовый класс CAction и список действий не будут зависеть от конкретного приложения. Также не будет необходимости в классе CUndoContext, предоставляющем доступ ко всей модели приложения. Вместо него можно передавать классы или интерейсы конкретных её частей. Например, операции перемещения фигуры достаточно передать указатель на фигуру + данные о ней.

Хранение и управление историей операций редактирования в приложении возложено на Presenter, что нарушает принцип единственной ответственности. Отчасти такое решение может являться следствием необходимости передачи UndoContext в действия.

Тут можно посмотреть описываемый мной [пример подхода к реализации истории Undo/Redo](https://github.com/alexey-malov/ood/tree/master/samples/command/iSpringWord/ISpringWord). Там можно взглянуть на класс CHistory и интерфейс ICommand.

**Comment by KonstantinGeist** [comment]
Я не вставил ссылки на посторонние объекты в конструктор CAction, т.к. хотелось, чтобы реализация команды была по возможности полностью реализована внутри самого CAction, включая определение текущего выделенного объекта. Например, если текущий выделенный объект записывался бы в конструктор CAction, то код нахождения текущего объекта и прочую инициализацию пришлось бы писать заново в каждом callsite конструктора, т.е. логика "размазана" по коду -- часть в callsite, а часть в самом CAction. В случае с Do(const CUndoContext& ctx) это инкапсулировано в одном месте. Также меньше проблем с lifetimes, т.к. контекст с ссылками на "внешний мир" просто даётся сверху по стеку, не нужно задумываться о том, кто держит ссылку на кого, и когда следует освобождать память. Согласен, что такой класс не reusable из-за специфичности CUndoContext. Хотелось бы спросить в порядке теории, было бы допустимым сделать CHistory шаблоном, где класс контекста - параметр шаблона? В таком случае класс был бы reusable.

**Comment by alexey-malov** [comment]
Речь шла про конструктор конкретных классов команд. Конструктор базового класса, разумеется, не должен содержать Application-specific вещей.

Насчёт вопроса допустимости сделать класс History шаблонным, параметризованным типом контекста. Возможно, это и сработало бы как решение созданной выше проблемы, но есть доводы против этого:

- Как History будет передавать контекст в Action?
-- Принимать его в методах Undo и Redo и передавать в Action::Undo/Redo?
-- Хранить контекст у себя? По ссылке или по указателю?
- Передавая контекст в Action::Undo() и Action::Redo() снаружи, есть риск передачи разных контекстов в разные вызовы, хотя требуется, чтобы контекст выполнения и отмены был одним и тем же. Самый простой и действенный способ это обеспечить - задавать контекст выполнения один раз - в момент конструирования Concrete Action.

В терминах паттерна "Команда" роль контекста играет Receiver (получатель команды). Роль Invoker-а (инициатор команды) - History. При этом они друг о друге ничего не знают - эти сведения инкапсулированы внутри команды.

**Comment by KonstantinGeist** [comment]
Я неточно выразился. Я имел в виду "посторонние объекты в конструкторы подклассов CAction". Например, при нажатии на DEL оптимистически генерируется команда CDeleteAction (с пустым конструктором), у которой сразу же вызывается Do(const CUndoContext& ctx), в котором реализована логика инициализации команды, специфичная для команды - в нашем случае, обращение к IDocumentView для определения текущего выделенного объекта, который следует удалить. Если оказывается, что выделенной фигуры нет, Do(..) возвращает false (отмена) и команда не добавляется в историю. Если выделенная фигура присутствует, возвращается true, объект удаляется (через обращение к IDocumentView опять же) и запоминается для последующего undo/redo. Таким образом, вся логика команды содержится в одном месте (в одном классе) - включая логику инициализации команды. Контекст был введён, чтобы логика инициализации команды (в нашем примере - нахождения текущего выделенного объекта) не была выведена в callsites за пределы класса.

**Comment by alexey-malov** [comment]
Против доступа к IDocumentView внутри команд у меня есть такой довод:
* Поддержка Undo/Redo является обязанностью модели. Модель не должна иметь зависимости от View. Полная зависимость от View в вашем случае и не нужна. Команде может понадобиться доступ к SelectionModel для смены выделения (например, при создании новой фигуры надо её выделить).
* IDocumentView

Каким образом selection вдруг оказался частью модели, а не представления? Модель может иметь несколько слоёв:
- Нижний слой: модель предметной области (холст с фигурами). Тут те объекты, которые в документе сохраняются.
- Модель приложения/представления (application model или presentation model). Тут selection и прочие динамические вещи (например, в видео-редакторе это может быть текущее время на таймлайне) могут появиться. Тут же управление историей размещается.

Визуальное отображение выделенной фигуры - обязанность View (или например его части: selection view).

**Comment by alexey-malov** [comment]
Логику создания команд - какой объект удалять и удалять ли вообще в зависимости от выделения - следует делать частью модели приложения. На этом уровне должны располагаться бизнес правила (что и когда можно делать).
Если размещать доступ ко всему контексту приложения внутри команд, то будет сильная связь между командой и приложением.

Представим себе следующий пример:
Надо добавить возможность Undo/Redo действий по изменению цвета заливки и обводки фигур. Если у команды будет зависимость от интерфейса IColorable, то один и тот же класс команд можно будет использовать как для изменения цвета заливки, так и для изменения цвета обводки:
```c++
class IColorable;
class ChangeColorCommand : public AbstractCommand
{
public:
    ChangeColorCommand(const shared_ptr<IColorable>& target, Color newColor)
        : m_target(target)
        , m_oldColor(target->GetColor());
        , m_newColor(newColor)
    {
    }
    void Undo() override
    {
        m_target->SetColor(m_oldColor);
    }
    void Redo() override
    {
        m_target->SetColor(m_newColor);
    }
private:
    shared_ptr<IColorable> m_target;
    Color m_oldColor;
    Color m_newColor;
}
```
Для создания цвета
```c++
// Изменить цвет заливки
m_history.AddCommand(make_shared<ChangeColorCommand >(shape->GetFillStyle(), newFillColor));
// Изменить цвет обводки
m_history.AddCommand(make_shared<ChangeColorCommand >(shape->GetOutlineStyle(), newOutlineColor));
```

**Comment by KonstantinGeist** [comment]
Да, я вижу, что если сделать undo/redo частью модели, то можно отображать history stack в другом view. У меня в данный момент этого сделать нельзя. Я согласен с доводами против CUndoContext. Не совсем ясно, как лучше следует определить application model. Это глобальный объект или частный для IDocumentView? Если посмотреть на мой класс IDocumentView, он по сути уже является довольно пассивным finite state UI, в котором операции переключают состояние и позволяют считывать состояние обратно, и не более (класс в целом виртуален и напрямую не зависит от MFC или каких-то фреймворков). Операции вроде Select/Drag/Hover симулируют намерения пользователя (передаваемые от MFC через Presenter), которые просто меняют состояние View, или игнорируются (с соответствующим ответом), и их можно тестировать изолированно. То есть IDocumentView по сути и является моделью приложения, за исключением метода Render(CDC* pDC). Как же в таком случае разделить IDocumentView на собственно IDocumentView и ApplicationModel (?)

**Comment by alexey-malov** [comment]
Примерно вот так:
![default](https://user-images.githubusercontent.com/6040682/35401272-1a3a9a84-020a-11e8-827f-b27739181020.png)

Некоторые вещи можно сделать проще, если вместо listener-ов использовать сигналы (например, из boost-а).
CanvasPresentation является прослойкой между CanvasPresenter и Canvas. Хранит как коллекцию ShapePresentation, так и отображение domain_model::Shape на pres_model::ShapePresentation.

На диаграмме показана примерная реализация добавления фигуры на холст:
* CanvasPresenter вызывает CanvasPresentation::AddShape через интерфейс pres_model::ICanvas
* Тот в свою очередь создаёт фигуру и выполняет команду добавления фигуры
* Команда добавления фигуры добавляет фигуру в коллекцию фигур доменной модели (класс Canvas::InsertShape) через интерфейс domain_model::IShapeCollection
* Метод Canvas::InsertShape сохраняет у себя фигуру и уведомляет слушателя о появлении новой фигуры
* CanvasPresentation реализует интерфейс domain_model::ICanvasListener и в методе OnShapeAdded() создает объект ShapePresentation, связанный с объектом доменной модели и запоминает соответствие в мапе m_shapeToPresentation и уведомляет слушателя о появлении новой фигуры через интерфейс pres_model::ICanvasListener
* Класс CanvasPresenter реализует интерфейс pres_model::ICanvasListener. Он создаёт при помощи view::ICanvasView объект IShapeView на нужном слое, создаёт ShapePresenter-а для него и сохраняет у себя ShapePresenter-а. 
* ShapePresenter настраивает ShapeView
* Потом команда добавления фигуры просит через IShapeSelector выделить добавленную фигуру доменной модели. CanvasPresentation выполняет выделение и уведомляет слушателя о смене выделения
* CanvasPresenter реагирует на событие о смене выделения и снимает выделение со старого CanvasPresenter-а (тот просит свой View снять выделение) и просит нового презентера установить выделение (тот просит свой View установить выделение).

Плюсы:
мы можем иметь несколько разных View одной и той же доменной модели (для них будут разные экземпляры (или даже группы классов) Presentaiton Model-и использоваться с соответствующими presenter-ами и view. Например: представление в виде холста и представление в виде таймлайна:

![default](https://user-images.githubusercontent.com/6040682/35401248-08a5a1ce-020a-11e8-9dd6-3613b7488f83.png)

**Comment by KonstantinGeist** [comment]
Всё понял. Application Model - это надстройка над Domain Model (состояние собственно документа), расширяющая её (в нашем случае) возможностью выделения объектов и историей (состояние приложения). Вместо общения с Domain Model напрямую, Presenter общается с Application Model, которая перенаправляет вызовы в Domain Model (и наоборот, через listener'ы).

Осталось рефакторить (скорее, вообще переписать) код. В процессе.

**Comment by alexey-malov** [comment]
Ок, буду ждать обновления

**Comment by KonstantinGeist** [comment]
Извините за задержку, пришлось переписывать заново, чтобы было как надо.
Сделал архитектуру из диаграммы -- View абсолютно пассивен (умеет только рисовать и сообщать о событиях ввода), вся логика - в Presenter'ах, состояние документа - в domain model (документ), состояние редактирования - в presentation model. Разумеется, ICommand теперь не имеет никаких контекстов.

**Comment by alexey-malov** [comment]
С Undo/Redo стало лучше.
От себя добавлю, что иногда в командах в дополнение к Execute() и Unexecute() добавляется метод Destroy(). Команды, выполняющие аллокацию каких-то внешних ресурсов (например, файлов и т.п.) могут в нём удалить или (не удалить) внешний ресурс. 
Примере, если при вставке изображения в документ, файл изображения копируется во временный каталог, то при удалении отменённой команды вставки изображения этот файл нужно будет удалить с диска. При удалении же выполненной команды вставки изображения (такое может произойти при ограниченной глубине истории) файл удалять не надо.
